# Training configuration for the hybrid music recommender system

# Model configuration
model:
  config_path: "configs/model_config.yaml"
  checkpoint_dir: "checkpoints"
  best_model_path: "checkpoints/best_model.pt"

# Data configuration
data:
  train_data_path: "data/preprocessed_1k_data/train_data.csv"
  val_data_path: "data/preprocessed_1k_data/validation_data.csv"
  test_data_path: "data/preprocessed_1k_data/test_data.csv"
  preprocessor_path: "data/preprocessed_1k_data/preprocessor.joblib"
  batch_size: 64
  num_workers: 4

# Features configuration
features:
  include_engineered: true

# Training configuration
training:
  # Basic training parameters
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 5
  early_stopping_delta: 0.001

  # Optimizer settings
  optimizer: "adam" # Options: adam, sgd, rmsprop
  scheduler: "reduce_on_plateau" # Options: reduce_on_plateau, cosine_annealing, step

  # Learning rate scheduler settings
  scheduler_patience: 3
  scheduler_factor: 0.5
  scheduler_min_lr: 1.0e-6

  # Loss function
  loss_function: "bce" # Options: bce, mse, cross_entropy

  # Gradient settings
  clip_gradients: true
  max_gradient_norm: 1.0

  # Regularization
  dropout_rate: 0.2
  l2_regularization: 0.0001

# Evaluation
evaluation:
  # Metrics to track
  classification_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "auc"

  # Ranking metrics
  ranking_metrics:
    - "ndcg@5"
    - "ndcg@10"
    - "map@5"
    - "map@10"
    - "hit_rate@10"

  # Primary metric for model selection
  primary_metric: "ndcg@10"

  # Whether higher is better for the primary metric
  higher_is_better: true

# Logging configuration
logging:
  log_dir: "logs"
  tensorboard_dir: "logs/tensorboard"
  log_interval: 10 # Log every N batches
  val_interval: 1 # Validate every N epochs
